version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ORCHESTRA_DB_HOST=db
      - ORCHESTRA_DB_PORT=5432
      - ORCHESTRA_DB_USERNAME=postgres
      - ORCHESTRA_DB_PASSWORD=postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres